# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Dan Spillane
title: Additive Engineering Design Graduate Researcher
email: DanielRSpillane@gmail.com
UniEmail: dks5230@psu.edu
#phone: dks5230@psu.edu
website: SpillaneMakes.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: SpillaneMakes
github_username: drspillane
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
linkedin_username: dan-spillane-173255b7
instagram_username: spillanemakes
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: SpillaneMakes Portfolio
  icon: DSLogo60px.ico
  url: SpillaneMakes.com
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: SpillanePic.JPG #(eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Daniel Spillane is a Master’s student in the School of Engineering Design, Technology, and Professional Programs (SEDTAPP) at Penn State. After completing a degree in Electrical Engineering and a Certificate in Engineering Design at Penn State in 2019, Dan continued his research with the Made by Design Lab, where he focuses on generative 3D modeling design tools for additive manufacturing. Dan is currently a Maker in Residence at Penn State’s Learning Factory where he teaches workshops on digital manufacturing techniques. He continues to volunteer time with student design organizations within SEDTAPP where he has been recognized with a distinguished student service award for his contributions to the department.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  As I finish my graduate degree at Penn State, I am actively seeking positions that incorporate my experience in additive manufacturing, 3D design, and machine learning applications. I enjoy working with the open-source and maker communities, and I am always looking to help with any projects focusing on design and tool development in additive manufacturing. If you are looking for an experienced 3D modeling, additive manufacturing professional, please feel free to reach out and contact me through my email listed below.


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
